version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.9.0
    steps:
      - checkout
      - run:
          name: check node version
          command: npm run preinstall
      - run:
          name: build the app
          command:  npm install
      - save_cache:
          name: Save app dependencies
          key: app-dependencies
          paths:
            - node_modules
      - run:
          name: lint app
          command: npm run lint
  test:
    docker:
      - image: cimg/node:17.9.0
    steps:
      - checkout
      - restore_cache:
          key: app-dependencies
      - run: npm run test
workflows:
  react-slingshot-ci:
    jobs:
      - build
      - test:
          requires:
            - build
